name: Full CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - 'feature/**'
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run Linter
      run: npm run lint
    
    - name: Run Unit Tests
      run: npm test
    
    - name: Generate Coverage Report
      run: npm run test:coverage

  local-publish-simulation:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Simulate Local Build
      run: |
        echo "Criando diretório de distribuição"
        mkdir -p dist
        cp -r src dist/
        cp package.json dist/
        echo "Simulação de build concluída"
    
    - name: Generate Artifact
      uses: actions/upload-artifact@v4
      with:
        name: local-build
        path: dist

  release:
    needs: [test, local-publish-simulation]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install Dependencies
      run: |
        npm ci
        npm install -D semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
